### PR TITLE
Added support for nix flakes

### PR DESCRIPTION
**Pull request by luftmensch-luftmensch**
As title suggested I thought It would be nice to add support for [nix-flakes](https://nixos.wiki/wiki/Flakes)

### CODE REVIEW

**Comment by luisnquin** [comment]
It would be nice to have both _default.nix_ and _flake.nix_ in order to support older versions of Nix

**Comment by luftmensch-luftmensch** [comment]
Yeah sure, you could maintain both of them

**Comment by luisnquin** [comment]
Flakes in this project sounds great! But it still is an experimental Nix feature, so it's not expected to be used by everyone.

https://nixos.org/manual/nix/stable/command-ref/new-cli/nix
https://zero-to-nix.com/concepts/flakes

Other argument for other separated _default.nix_ file is that in that way the nix code seems less complex looking more modularized

**Comment by luisnquin** [comment]
Sorry I just noticed that you didn't deleted the _default.nix_ haha but a better approach is to import the file from your _flake.nix_ instead of copy-pasting the content of the original file

**Comment by luftmensch-luftmensch** [comment]
As you can see i used the directives from the `default.nix` updated with the built-in function `fetchFromGitHub`

I also updated the README and make code formatting

**Comment by luisnquin** [comment]
Two things:
 - Remove the symbolic link _result_, this is only referencing a place of your local _/nix/store_
 - `nix run github:gabrielzschmitz/Tomato.C` in the README seems better to me

After that changes everything looks good to me @gabrielzschmitz 

Soon I'll add a CI to keep the default.nix file updated

**Pull request merged**
